import type { NavGroup } from '../types/admin.types';

export const ADMIN_NAV: NavGroup[] = [
  {
    label: 'Principal',
    items: [
      {
        key: 'dashboard',
        label: 'Dashboard',
        icon: 'LayoutDashboard',
        path: '/admin',
        roles: ['super_admin', 'admin', 'coordinator'],
        moduleKey: 'dashboard',
      },
    ],
  },
  {
    label: 'Gestão',
    items: [
      {
        key: 'appointments',
        label: 'Agendamentos',
        icon: 'CalendarCheck',
        path: '/admin/agendamentos',
        roles: ['super_admin', 'admin', 'coordinator'],
        moduleKey: 'appointments',
      },
      {
        key: 'enrollments',
        label: 'Pré-Matrículas',
        icon: 'GraduationCap',
        path: '/admin/matriculas',
        roles: ['super_admin', 'admin', 'coordinator'],
        moduleKey: 'enrollments',
      },
      {
        key: 'contacts',
        label: 'Contatos',
        icon: 'MessageSquare',
        path: '/admin/contatos',
        roles: ['super_admin', 'admin', 'coordinator'],
        moduleKey: 'contacts',
      },
      {
        key: 'attendance',
        label: 'Atendimentos',
        icon: 'Ticket',
        path: '/admin/atendimentos',
        roles: ['super_admin', 'admin', 'coordinator'],
        moduleKey: 'attendance',
      },
    ],
  },
  {
    label: 'Qualificação',
    items: [
      {
        key: 'kanban',
        label: 'Kanban de Leads',
        icon: 'Kanban',
        path: '/admin/leads/kanban',
        roles: ['super_admin', 'admin', 'coordinator'],
        moduleKey: 'kanban',
      },
      {
        key: 'reports',
        label: 'Relatórios',
        icon: 'BarChart2',
        path: '/admin/relatorios',
        roles: ['super_admin', 'admin', 'coordinator'],
        moduleKey: 'reports',
      },
    ],
  },
  {
    label: 'Escola',
    items: [
      {
        key: 'segments',
        label: 'Segmentos e Turmas',
        icon: 'School',
        path: '/admin/segmentos',
        roles: ['super_admin', 'admin', 'coordinator'],
        moduleKey: 'segments',
      },
      {
        key: 'students',
        label: 'Alunos',
        icon: 'UserCheck',
        path: '/admin/alunos',
        roles: ['super_admin', 'admin', 'coordinator'],
        moduleKey: 'students',
      },
      {
        key: 'teacher-area',
        label: 'Área do Professor',
        icon: 'BookOpen',
        path: '/admin/area-professor',
        roles: ['super_admin', 'admin', 'coordinator', 'teacher'],
        moduleKey: 'teacher-area',
      },
      {
        key: 'library',
        label: 'Biblioteca Virtual',
        icon: 'Library',
        path: '/admin/biblioteca',
        roles: ['super_admin', 'admin', 'coordinator', 'teacher'],
        moduleKey: 'library',
      },
      {
        key: 'announcements',
        label: 'Comunicados',
        icon: 'Megaphone',
        path: '/admin/comunicados',
        roles: ['super_admin', 'admin', 'coordinator', 'teacher'],
        moduleKey: 'announcements',
      },
      {
        key: 'events',
        label: 'Eventos',
        icon: 'CalendarDays',
        path: '/admin/eventos',
        roles: ['super_admin', 'admin', 'coordinator', 'teacher'],
        moduleKey: 'events',
      },
      {
        key: 'testimonials',
        label: 'Depoimentos',
        icon: 'MessageSquare',
        path: '/admin/depoimentos',
        roles: ['super_admin', 'admin', 'coordinator'],
        moduleKey: 'testimonials',
      },
    ],
  },
  {
    label: 'Sistema',
    items: [
      {
        key: 'audit',
        label: 'Auditoria',
        icon: 'FileSearch',
        path: '/admin/auditoria',
        roles: ['super_admin', 'admin'],
        moduleKey: 'audit',
      },
      {
        key: 'permissions',
        label: 'Permissões',
        icon: 'Shield',
        path: '/admin/permissoes',
        roles: ['super_admin', 'admin'],
        moduleKey: 'permissions',
      },
      {
        key: 'users',
        label: 'Usuários',
        icon: 'Users',
        path: '/admin/usuarios',
        roles: ['super_admin', 'admin'],
        moduleKey: 'users',
      },
      {
        key: 'settings',
        label: 'Configurações',
        icon: 'Settings',
        path: '/admin/configuracoes',
        roles: ['super_admin', 'admin'],
        moduleKey: 'settings',
      },
    ],
  },
];
