// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Fail-safe: pass stub values when env vars are missing so module init doesn't
// throw "supabaseUrl is required" and crash the bundle before React mounts.
// The banner in src/lib/supabase.ts explains what to configure.
export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://missing-env.invalid',
  SUPABASE_PUBLISHABLE_KEY || 'missing-env-key',
  {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);
